In [7]:
# a.Using NumPy create random vector of size 15 having only Integers in the range 1-20.
import numpy as np
randVect = np.random.randint(low=1, high=21, size=15)
print("Original array: ", randVect)

Original array:  [ 3  4  9 11  2 16 18  6 16 18 17  1  9  4  2]


In [11]:
# a1. Reshape the array to 3 by 5
array = randVect.reshape(3,5)
print("Reshaped array: ")
print(array)

Reshaped array: 
[[ 3  4  9 11  2]
 [16 18  6 16 18]
 [17  1  9  4  2]]


In [13]:
# a2. Print array shape.
arrayShape = array.shape
print(arrayShape)

(3, 5)


In [15]:
# a3. Replace the max in each row by 0
max_indices = np.argmax(array, axis=1) #argmax chooses the maximum value from the array, axis=1 chooses from each row
array[np.arange(array.shape[0]), max_indices] = 0
print("Modified array:")
print(array)

Modified array:
[[ 3  4  0  0  2]
 [16  0  6 16  0]
 [ 0  1  0  4  2]]


In [21]:
# Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type
# of the array
import numpy as np
arr2 = np.array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]], dtype= np.int32)
print("Shape of array:", arr2.shape)
print("Type of array:", type(arr2))
print("Data type of array:", arr2.dtype)

Shape of array: (4, 3)
Type of array: <class 'numpy.ndarray'>
Data type of array: int32


In [28]:
# b. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
## [[ 3 -2] [ 1 0]]

arr3 = np.array([[3,-2], [1,0]])
eigenValues, eigenVectors = np.linalg.eig(arr3) # linalg module in numpy library has eig function to find eigen values and vectors
print("Eigenvalues:")
print(eigenValues)
print("\nRight Eigenvectors:")
print(eigenVectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [32]:
# c. Compute the sum of the diagonal element of a given array.
## [[0 1 2] [3 4 5]]

arr4 = np.array([[0,1,2], [3,4,5]])
sumOfDiagonalElement = np.trace(arr4) #trace() function is used to return the sum of the diagonals of the matrix.
print("Sum of Diagonal Element:", sumOfDiagonalElement)

Sum of Diagonal Element: 4


In [35]:
# Write a NumPy program to create a new shape to an array without changing its data.
# Reshape 3x2: 
# [[1 2]       
# [3 4]
# [5 6]]

# Reshape 2x3:
# [[1 2 3]
# [4 5 6]]

arr5 = np.array([[1,2], [3,4], [5,6]])
reShape3By2 = arr5.reshape(2,3)
print("Reshaping 3x2 to 2x3 \n", reShape3By2)

arr6 = np.array([[1,2,3], [4,5,6]])
reShape2By3 = arr6.reshape(3,2)
print("Reshaping 2x3 to 3x2 \n", reShape2By3)


Reshaping 3x2 to 2x3 
 [[1 2 3]
 [4 5 6]]
Reshaping 2x3 to 3x2 
 [[1 2]
 [3 4]
 [5 6]]
